### ISSUE TITLE
Alpha bugs list

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-android#1]
- [x] password not validated or saved on sign up - can't continue sign in
- [x] color theme on description is LBRY green (hyperlinks / tags)
- [ ] blue ribbon at top of wallet page goes to rewards page that doesn't work. Blue ribbon is not within color theme. 
- [x] remove USD equivalents ? 
- [x] channel discover page doesn't load - this should load channels from primary category, sorted by trending? 
- [x] should be able to click entire comment to expand all comments, not just the expand button.
- [x] Improve single comment picking. It is just selecting comment 0, even if it won't be displayed on expanded list
- [ ] when signed out, drive sign up if you try to react, comment, etc. 
- [ ] When no channel available and required, drive channel creation
- [x] comments page on channel page shows bad data - check @saltycracker channel, only has 1 comment  
- [x] no search / url bar? 
- [x] when you sign out, wallet balance still shows, notification page blank
- [x] Bittrex conversion link > https://lbry.com/faq/exchanges. Call it "Exchange your Credits" - or ask Jeremy for the Copy for this.
- [x] Can't comment: authentication required
- [x] After reacting, comments collapse. Can't see total reactions after you react. (can't seem to react anymore)
- [x] Clicking video from pop out player goes to homepage.
- [x] Can't navigate home after a few videos deep via related.(have to keep clicking back through each page).
- [x] New content notification click ends up in 'loading decentralized data for a while (no need to mention decentralized mention). Other navigation steps too, even after being available in claim search.
- [ ] on sign up, email sent to is black, can't see the email
- [ ] Odysee often disappears from the quick switcher - need to find the app again. Happens when I navigate away to another app? This happens on the sign in page for sure (i..e go to check email for confirmation link, disappears)
- [x] view more on wallet page expands to a blank item (no additional breakdown shown)
- [x] remove all references to USD stuff
- [x] app crash with samsung
- [x] changes to followings in app seem to only be stored locally (wallet sync is off, added to top missing features)
- [x] has option to follow channels you are already following
- [x] Following page feels bloated(top bar + channels you follow + navigation bar takes about half of the screen )
- [ ] view history (sign out or view + sign in - should clear maybe?), including notifications is persisted between sessions 
- [x] floating player covers navigation bar at the bottom
- [x] resolve notification data to get channel and claim thumbnails for notifications area 
- [ ] fireabase token persisted between uninstall/reinstall. Getting old notifications from the previous account. Never saw this before - apis issue? 
- [ ] pop out player gets stuck to top of trending somehow (notice it's both at the top and bottom - small thumbnail, I was scrolled up) 
![image](https://user-images.githubusercontent.com/8120721/132720109-dad3f271-ea40-45fb-9965-2203797e11a7.png)
- [x] pop out player shows on non-video content (minimize while on random page) 
![image](https://user-images.githubusercontent.com/8120721/132720005-3aa297e9-00db-4bcd-af2a-1762a1394c5d.png)
- [x] Livestreams are no longer listed on the Following fragment
- [x] Make progress bar Odysee theme
- [x] Julian got stuck at "retrieving account information" - had to close/reopen
- [x] Julian getting random crashes, doesn't seem consistent on anything in particular. I got a few while navigating around as well.
- [x] remove details on sign in about wallet sync (streamline)
- [x] search both content and channels for top result (i..e thomas.zarebczan would search @thomas.zarebczan) (julian noticed this)
- [x] you can get the bottom navigation items to show during search, but clicking them doesn't do anything 
- [ ] auto search after typing + waiting x seconds? 
- [ ] allow magic link login on the password prompt.
- [ ] playlists on channel page - look strange without thumbnail, cannot view content error when clicking one without thumbnail. With thumbnail, it shows the thumbnail on top and loading icon over it, and then the typical file view. playlist items are way at the bottom. Probably want to start without the details page and just show the playlist items, with current item playing on top. 
- [x] livestreams don't play (tried direct link - probably needs urls updated to odysee ones)
- [x] notifications are marked read only in the session - when I quit app + restart, I see 50+ on bell, and those I recently watched are not marked as read anymore.
- [x] search shows a spinning bar in top right even if you aren't searching anything
- [ ] remove search text "you can search..." - match ios - "start typing to discover" with lasso spaceman
- [x] Make commenting flow colors odysee theme (saw green stuff)
- [x] Make search flow Odysee colors (green on channel links)
- [x] reacting to content is super slow - count does not increment. 
- [x] notifications page takes over other pages, no clear way to close besides clicking back. If you click notification, and then search, it shows the search box with notifications in backgroud
- [x] authentication error when tipping
- [x] swipe gestures close app (Akin thinks this may be causing what Julian is seeing)
- [x] remove "loading decentralized data" references 
- [x] Odysee notification icon - make Odysee colors (it's green today)

missing features:
- wallet sync
- reward verification via phone/twitter/cc/paid
- livestreams (showing on channel page , live stream comments at least)
- yt sync flow
- first run flow (claiming email verified reward or maybe the android one we have - both are fine too, channel setup or YT sync, follow channels) 
- comment reactions
- rewards
- channel creation
- checking for disabled comments on channels (see ios implementation)
- playlists

Will add more here as I find it, anyone else is free to edit/add also. 

Fixed:
- [x] Blank trending homepage when navigating back to it. Clicking new (loads) and then trending again works. Categories are lost in this case.
- [x] sign in goes to a sign up flow. Add option to sign in? 
- [x] Sign in proces shows "join odysee"
- [x] buy LBRY credits pops up a strange overlay. This can probably be modeled after odysee.com buy screen or remove for now. 
- [x] yerbil > space man 
- [x] user and install new needs to pass odysee.com as the domain - otherwise you get LBRY related emails
- [x] wildwest > all content, don't pass any channel ids + only allow trending
- [x] Makes my notification bar black, can't see any icons/text. (Phone in dark mode).
- [x] seek bar on video is LBRY themed
- [x] are we optimizing spee.ch thumbnails to a reasonable size? maybe use the ones that odysee.com is using so they are properly cached. Lazy loading feels sluggish
- [x] Share buttons link to lbry.tv, should by odysee.com
- [x] Wallet: "View All" shows incorrectly "There are no transactions to display"

Some new stuff from the recent beta (12/17):
- reports of crashing on email verification
- can't see comments after posting
- need comment edit/delete options
- wild west still looks filtered (that was checked off above)
- thumbnails not loading in notifications
- Fix odysee colors on wallet page (green) 
- Remove "exchange your credits" link 
- when supporting and entering an amount, need to click into field twice to get keyboard to pop up
- livestreams not brought to top of channel page. Need to account for scheduled streams also.

**Comment by tzarebczan** [comment]
- [ ] Makes my notification bar black, can't see any icons/text. (Phone in dark mode).
- [ ] Can't comment: authentication required
- [ ] After reacting, comments collapse. Can't see total reactions after you react.
- [ ] Clicking video from pop out player goes to homepage.
- [ ] Can't navigate home after a few videos deep via related.(have to keep clicking back through each page).
- [ ] Blank trending homepage when navigating back to it. Clicking new (loads) and then trending again works.
- [ ] New content notification click ends up in 'loading decentralized data for a while (no need to mention decentralized mention). Other navigation steps too, even after being available in claim search.

**Comment by iamflorencejay** [comment]
![image](https://user-images.githubusercontent.com/24932514/130712905-26c9876e-7715-4510-a78c-eace73666790.png)

I've seen a certificate error when installing the package. Probably on APK build.

**Comment by iamflorencejay** [comment]
> > By the way, AsyncTask is deprecated in Android 11, so I see the problem here.
> 
> That's unrelated to the signature problem.
> 
> AsyncTask was deprecated, but not yet removed. All my new code was also using Java Futures instead of AsyncTask

I see. But I think it will be removed in the future though. So yep, patch it up.

**Comment by keikari** [comment]
Issues from reddit thread
* [ ] changes to followings in app seem to only be stored locally
* [ ] floating player covers navigation bar at the bottom
* [ ] Wallet: "View All" shows incorrectly "There are no transactions to display"
* [ ] Report about similar behavior with background playback as this https://github.com/lbryio/lbry-android/issues/1206
- Battery optimization disabled
- Pixel 4A Android 11
- Samsung Galaxy S9 with Android 10

**Comment by julianchandra** [comment]
Feature request for first run:
Ability to send tip - if it's taking this long to release, we may as well have this bit ready.

**Comment by iamflorencejay** [comment]
> Feature request for first run:
> Ability to send tip - if it's taking this long to release, we may as well have this bit ready.

This will happen probably on Google's in app purchases, not stripe.

**Comment by julianchandra** [comment]
I've been playing around with odysee android alpha. Probably not ready for release yet.
A couple of things that I noticed that were were problematic:
If I go out of the app even just for a few seconds to check another app and return, the odysee app restarts.
Searching for channels: Search for a channel, e.g. laowhy86, you'll see 'nothing is here' at the top, then the laowhy86 channel, and then some of his videos. If you click the channel below the 'nothing is here' nothing happens. So users can't view channel pages yet

**Comment by PeterKW** [comment]
Any idea/updates on when private lists will be watchable in the app?  https://odysee.com/$/lists

**Comment by kekkyojin** [comment]
Livestreams are again listed on the Following fragment. Fixed on branch, will be merged on master branch. This will come along the fix for livestream play and a few of threading API changes -my code was using Future.get(), which was blocking Android UI thread; the branch changes it-. This branch will should also make the content Reaction code faster, as it will no longer block the main thread.

**Comment by kekkyojin** [comment]
> pop out player gets stuck to top of trending somehow (notice it's both at the top and bottom - small thumbnail, I was scrolled up)

The item on the top is certainly not the same. Mini player -the one at the bottom- is using a explicitly different layout than list items. Also look at the background color.

What is happening is that somehow recyclerview is using the list item's layout for smaller screens for the one on the top. Odysee Android added a new layout for items to be used on more common screens nowadays, which have more pixels available and can show the thumbnail side-to-side of the screen. But the older layout remained, as older or cheaper -with lower resolution- phones can use it instead.

It looks like some graphic artifact from the Android OS.

What shouldn't be happening at all is that top item to be stuck there.

**Comment by BobIsMyManager** [comment]
Are downloads every going to be added?
